### ISSUE TITLE
Change the eslint-plugin-vue-a11y peer dependency

### ISSUE THREAD

**Issue by DanWebb** [boughtbymany/eslint-config-bbm#27]
[eslint-plugin-vue-a11y](https://github.com/maranran/eslint-plugin-vue-a11y) appears to be no longer maintained and is causing peer-dependency installation issues on npm v7+.

Could we fix this by using the more up to date [eslint-plugin-vuejs-accessibility](https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility) instead?

CC: @gavmck a while back now, I remember you suggested there was an issue with using eslint-plugin-vuejs-accessibility, can you remember what the issue was? If not, I'll run some tests with and create a PR for this when I get a mo.

**Comment by gavmck** [comment]
@DanWebb There was a problem with it at the time that was breaking the build.

Looks like it's been fixed now: https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility/issues/62
